"""user_id and oauth_key must be not null in OAuthUserCredentials model

Revision ID: 3296a17debd3
Revises: 5888f47464a2
Create Date: 2016-10-10 17:48:22.364571

"""

# revision identifiers, used by Alembic.
from __future__ import division

revision = '3296a17debd3'
down_revision = '5888f47464a2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.alter_column('oauth_user_credentials', 'oauth_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('oauth_user_credentials', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_user_credentials', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('oauth_user_credentials', 'oauth_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
