"""Add timestamp and managed_by_authenticator column to UserToUserGroup association class.

Revision ID: 3ba37c887c16
Revises: 6e37c3bcacf
Create Date: 2015-12-18 17:19:23.601730

"""

# revision identifiers, used by Alembic.
from __future__ import division

revision = '3ba37c887c16'
down_revision = '6e37c3bcacf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    op.add_column('user_to_usergroup', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_to_usergroup', sa.Column('managed_by_authenticator', sa.Boolean(), server_default='false', nullable=True))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_to_usergroup', 'managed_by_authenticator')
    op.drop_column('user_to_usergroup', 'created_at')