# -*- coding: utf-8 -*-
'''
HTTP status codes from athana used by mediaTUM
'''

HTTP_OK = 200
HTTP_MOVED_TEMPORARILY = HTTP_FOUND = 302
HTTP_BAD_REQUEST = 400
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_NOT_ACCEPTABLE = 406
HTTP_INTERNAL_SERVER_ERROR = 500